version: "3.8"  # Use version 3.x (remove 'version' if it's causing warnings)
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db  # Ensure the web service depends on db
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest  # Official pgAdmin image
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Replace with your preferred email
      PGADMIN_DEFAULT_PASSWORD: admin  # Replace with your preferred password
    ports:
      - "5050:80"  # Exposing pgAdmin web interface on port 5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persistent storage for pgAdmin
    networks:
      - default
    depends_on:
      - db  # Ensure pgAdmin waits for the db to be ready

volumes:
  pgdata:
  pgadmin_data:
